logging:
  level: INFO
  loggers:
    com.colloquio: DEBUG
organisation:
  name: "Podacio"
database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password:
  url: jdbc:mysql://localhost:3306/colloquio
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
