logging:
  level: INFO
  loggers:
    com.colloquio: DEBUG
organisation:
  name: "Podacio"
database:
  driverClass: org.postgresql.Driver
  user: colloquio
  password: hola-colloquio
  url: jdbc:postgresql://localhost:5432/colloquio
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
swagger:
  resourcePackage: com.colloquio.resources
